language: python

python: "3.3"

install:
    - pip install .
    - pip install coverage
    - pip install coveralls

script:
    - coverage run --source=simplecrypto simplecrypto/tests/test.py
    - coverage report -m

after_success: coveralls --verbose
