language: python

python: "3.3"

install:
    - pip install coverage
    - pip install coveralls
    - pip install .

script: coverage --source simplecrypto run simplecrypto/tests/test.py

after_success: coveralls
