language: python

python:
  - "3.3"
  - "3.2"
  - "2.7"

install:
    - pip install coverage
    - pip install coveralls
    - pip install .

script: coverage run simplecrypto/tests/test.py

after_success: converalls
